name: Install Requirements.txt

on: pull_request

jobs:
  test_requirements_txt:
    runs-on: ubuntu-22.04  # Ubuntu 22.04 LTS (Jammy Jellyfish)
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    #help to identify if dependabot PRs can be closed without conflict
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
